name: NPM audit fix
on:
  workflow_dispatch:
jobs:
  npm-audit-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: miyajan/npm-audit-pr@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
